# Type
- name: community
  color: d93f0b
  description: ''

- name: discussion
  color: bebaf4
  description: Topics for discussion. Might end in an enhancement or question label.

- name: infrastructure
  color: 006b75
  description: Infrastructure related issue

- name: content
  color: 0052cc
  description: Content related issue

- name: usage question
  color: a2eeef
  description: User questions which do not appear to be bugs or enhancements.

- name: enhancement
  color: fbca04
  description: Issues that are found to be a reasonable candidate feature additions

- name: bug
  color: B60205
  description: Issues that present a reasonable conviction there is a reproducible bug.

- name: external-links-gallery-submission
  color: a89b97
  description: Issue used for updating external links gallery

# Events
- name: hackathon
  color: a03f0b
  description: Issue highlighted for active hackathon session

# Skill level
- name: good first issue
  color: '159818'
  description: Clearly described and easy to accomplish. Good for beginners to the project.

- name: good second issue
  color: 5319e7
  description: Clearly described, educational, but less trivial than "good first issue".

# Status
- name: needs info
  color: f4e49a
  description: If more info has been requested from the author, apply this label.

- name: blocked
  color: b60205
  description: Awaiting the output of some other work

- name: stale
  color: D3D3D3
  description: ''

- name: needs triage
  color: 7b9ad8
  description: 'This can be kept if the triager is unsure which next steps to take'

- name: ready for review
  color: 0e8a16
  description: ''

- name: ready to merge
  color: c9e7c7
  description: ''

# Priority
- name: high priority
  color: fbca04
  description: High priority issue

- name: medium priority
  color: fef2c0
  description: Medium priority issue

- name: low priority
  color: c2e0c6
  description: Low priority issue
